# Generated by Django 5.0 on 2024-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Electronics', 'Electronics'), ('Health Care', 'Health Care'), ('Pet Care', 'Pet Care'), ('Household & Cleaning Supplies', 'Household & Cleaning Supplies'), ('Tools', 'Tools')], max_length=30, null=True),
        ),
    ]
